### PR TITLE
Make example.php script readable in CLI and browser.

### PR DESCRIPTION
**Pull request by kevindecapite**
Per a request from @AstroSign-Dev the `example.php` script can be run from the terminal or the browser with its results displaying coherently.

### CODE REVIEW

**Comment by aloistr** [comment]
Example is of limited value because it requires root permission to set  up an ephemeris directory cooy on the given path.
Docker is no workaround because it also allows access to docker.sock only as root.
Example moght work better if it used the given ephemeris directory ./sweph/ephe

**Comment by kevindecapite** [comment]
I think many people will end up running `example.php` from their browser since PHP is typically a web language. So the SE data files path will be completely custom to their server environment anyway; but it runs just find from the CLI using relative paths now.

**Comment by aloistr** [comment]
You know that one can use a multi-part path with sections separed by semicolons or colons?
On Windows, only semicolons.
That means ".:./sweph/ephe:/root/php-sweph/sweph/ephe" will work

to make it Windows compatible, conditional code would be needed, as paths in Windows have \ as directory separator. One of the more stupid decisions of Bill Gates, for Msdos.

**Comment by kevindecapite** [comment]
> one can use a multi-part path with sections separed by semicolons or colons

Yes, I do know that, but didn't think to add all of that into the little example file.

Regarding the slashing nonsense across platforms, `DIRECTORY_SEPARATOR` is your friend:
```
$paths = [
    ['.'],
    ['.', 'sweph', 'ephe'],
    [DIRECTORY_SEPARATOR . 'root', 'php-sweph', 'sweph', 'ephe'],
];

$translatedPaths = array_map(function ($pathParts) {
    return join(DIRECTORY_SEPARATOR, $pathParts);
}, $paths);

var_dump(join(':', $translatedPaths));

# Outputs
string(41) ".:./sweph/ephe:/root/php-sweph/sweph/ephe"
```
...and of course on Windows, those would be `\`.

**Review by aloistr — APPROVED** [review]

**Pull request merged**
