### PR TITLE
added #ifdef __CYGWIN__ to compile correctly with cygwin

### PR DESCRIPTION
**Pull request by aloistr**
the change in sweodef.h is harmless and overdue fpr cygwin support in Swiss Ephemeris.
The issue of building a dynamical library as php extension on Windows remains

### CODE REVIEW

**Review by kevindecapite — COMMENTED** [review]
I cannot test this as I'm away from my office and don't have a Windows computer with me. 

My main question at the moment is:

__Why change source files when they will be overwritten on the next SE library update?__

This also makes me think we should really use a Git submodule for bringing the SE library code into this extension. This way no manual work has to be performed when the core library is updated:

> The issue with copying the code into your own project is that any custom changes you make are difficult to merge when upstream changes become available.

From: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by aloistr** [comment]
I am not sure how this submodule concept should work both locally for me, and for an external user who clones from github.

One could say that php-sweph always depends on the released https://github.com/aloistr/swisseph repo.
But what if I have locally an unreleased swisseph branch, and want to test an unreleased php-sweph branch using that version?

**Comment by kevindecapite** [comment]
> But what if I have locally an unreleased swisseph branch, and want to test an unreleased php-sweph branch using that version?

You would simply checkout the appropriate submodule branch locally while testing, etc. I haven't used submodules very much and need to read more about them as well to gain a better understanding. Then we can make a decision as to whether or not they would be a good solution.

If so, it may be appropriate to use them for the Perl project you are now starting, too. I will see if I can contribute there as well, but it has been a long time since I programmed in Perl.

**Comment by astrorigin** [comment]
The problem with submodules and Github is that you will be unable to make releases because the source distribution does not include the code of the submodules, but only the code of the current repo. That is a know "bug" and we do not know if/when Github will fix that.
Other than that submodules are great. We use them in Pyswisseph.

**Comment by kevindecapite** [comment]
> The problem with submodules and Github is that you will be unable to make releases because the source distribution does not include the code of the submodules, but only the code of the current repo. That is a know "bug" and we do not know if/when Github will fix that.

Thank you for letting us know about that. I think the extension should be as self-contained/portable as possible. So I would vote against the submodule idea at this time.

**Pull request merged**
